import { Provider } from "@/components/provider";
import type { Metadata } from "next";
import "./globals.css";
import NavHeaderClient from "@/components/layout/NavHeaderClient";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
<<<<<<< HEAD
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavHeaderClient />
          {children}
        </Provider>
      </body>
    </html>
  );
=======
	return (
		<html lang="en">
			<body className="antialiased">
				<Provider>{children}</Provider>
			</body>
		</html>
	);
>>>>>>> origin/dev
}
